name: scam_burst
description: AI-powered scam protection for senior citizens.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0                      # For FastAPI requests
  flutter_background_service: ^5.0.5 # Keeps app alive
  system_alert_window: 2.0.7       # Shows Red Alert Popup
  permission_handler: ^11.3.0     # Asks for permissions
  shared_preferences: ^2.2.0
  notification_listener: ^1.0.2+1
  url_launcher: ^6.2.0              # For launching SMS/calls
  
dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  